# Generated by Django 4.2.7 on 2025-12-26 14:50

from django.db import migrations, models
import django.db.models.deletion
import uuid_utils.compat

class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_remove_knowledgeworkflowversion_workflow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraphBinding',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('instance_id', models.CharField(max_length=255, verbose_name='第三方实例ID')),
                ('knowledge', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='graph_bindings', to='knowledge.knowledge', verbose_name='知识库')),
            ],
            options={
                'verbose_name': '知识图谱关联',
                'db_table': 'knowledge_graph_binding',
            },
        ),
    ]
