# Generated by Django 5.2.9 on 2025-12-30 14:18

import django.db.models.deletion
import uuid_utils.compat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_remote_knowledgeworkflowversion_workflow_and_more.py'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeKagConfig',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid_utils.compat.uuid7, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('kag_url', models.URLField(verbose_name='KAG系统地址')),
                ('kag_token', models.CharField(max_length=512, verbose_name='KAG Token')),
                ('task_name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('llm_config_id', models.IntegerField(blank=True, null=True, verbose_name='LLM配置ID')),
                ('embedding_config_id', models.IntegerField(blank=True, null=True, verbose_name='Embedding配置ID')),
                ('prompt_id', models.CharField(blank=True, max_length=64, null=True, verbose_name='Prompt ID')),
                ('extraction_rounds', models.IntegerField(default=1, verbose_name='抽取轮数')),
                ('knowledge', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='kag_config', to='knowledge.knowledge', verbose_name='知识库')),
            ],
            options={
                'db_table': 'knowledge_kag_config',
            },
        ),
    ]
