# Generated by Django 5.2.9 on 2026-01-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0009_knowledgekagconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgekagconfig',
            name='kag_pipeline_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='KAG Pipeline配置'),
        ),
    ]
